### ISSUE TITLE
DeepDetect client python module error

### ISSUE THREAD

**Issue by acabrol** [soprasteria/cybersecurity-dfm#1]
Since the commit: https://raw.githubusercontent.com/beniz/deepdetect/d2c404e43cc25ff802e5d053aad55ed032c9ed83/clients/python/dd_client.py

The class DDCommunicationError doesn't exist anymore. This impact DFM main module start and crash the daemon.

**Comment by tmaurelsoprasteria** [comment]
Made a quick fix on the installation script at 92f3547720713d462e9bcf79af0c81510dd1dd03. Just a checkout on the right commit.
